import directoryJson from '@/data/lending-libraries.json';

// Typed view over src/data/lending-libraries.json (generated by
// scripts/parse-lending-directory.mjs from docs/content/directory-lending-libraries.md).

export interface DirectoryEntry {
  name: string;
  city: string;
  type: string;
  description: string;
  address: string | null;
  hours: string | null;
  url: string | null;
  verified: boolean;
  verifiedNote: string | null;
}

export interface DirectoryState {
  name: string;
  entries: DirectoryEntry[];
}

export interface LendingDirectory {
  snapshot: string;
  states: DirectoryState[];
}

export const LENDING_DIRECTORY = directoryJson as LendingDirectory;

/** "District of Columbia" → "district-of-columbia" (per-state anchors, BUILD_SPEC). */
export function stateSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z]+/g, '-');
}
